{
  "name": "expense-tracker-backend",
  "env": "node",
  "buildCommand": "npm install",
  "startCommand": "node server.js",
  "envVars": [
    {"key": "MYSQL_HOST", "value": "gondola.proxy.rlwy.net"},
    {"key": "MYSQL_PORT", "value": "27737"},
    {"key": "MYSQL_USER", "value": "root"},
    {"key": "MYSQL_PASSWORD", "value": "DPHhMBJuYlcQlaeZmXsFGgUZZLkqrhhX"},
    {"key": "MYSQL_DATABASE", "value": "railway"}
  ]
}
