services:
  - type: web
    name: expense-tracker-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MYSQLHOST
        value: gondola.proxy.rlwy.net
      - key: MYSQLPORT
        value: 27737
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: DPHhMBJuYlcQlaeZmXsFGgUZZLkqrhhX
      - key: MYSQLDATABASE
        value: railway
